sudo: required
language: generic
services:
  - docker

after_success:
  - docker build -t gmatysik/northwindmvc -f ./NorthwindMvc/Dockerfile.dev ./NorthwindMvc
  - docker build -t gmatysik/northwindservice -f ./NorthwindService/Dockerfile.dev ./NorthwindService
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
