sudo: required
language: generic
services:
  - docker

after_success:
  - docker build -t gmatysik/northwindmvc -f ./NorthwindMvc/Dockerfile.dev ./NorthwindMvc
  - docker build -t gmatysik/northwindservice -f ./NorthwindService/Dockerfile.dev ./NorthwindService
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gmatysik/northwindmvc
  - docker push gmatysik/northwindservice

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-dotnet
  env: MultiDotnet-env
  bucket_name: elasticbeanstalk-eu-central-1-413281467786
  bucket_path: dotnet-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY